name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: klatt42/fbm-auth/.github/workflows/python-ci.yml@main
    with:
      working-directory: .
      has-frontend: false
